# Generated by Django 4.2.4 on 2023-08-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Posted Date and Time')),
                ('category', models.CharField(choices=[('technology', 'ITのこと'), ('daily life', '日常のこと'), ('music', '音楽のこと'), ('portfolio', '自作製品のこと')], max_length=50, verbose_name='Category')),
            ],
        ),
    ]
