# Generated by Django 4.2.4 on 2023-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('technology', 'ITのこと'), ('dailylife', '日常のこと'), ('music', '音楽のこと'), ('portfolio', '自作製品のこと')], max_length=50, verbose_name='Category'),
        ),
    ]
